# Generated by Django 5.2.4 on 2025-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(),
        ),
    ]
